branches:
    only:
        - master
        - feat/test_CI


language: cpp

matrix:
    include:
        - os: linux
          env: PYTHON=3.6

compiler:
        - gcc

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake

install:
       - mkdir build
       - cd build
       - cmake .. -DENABLE_DOC=YES



##before_install: sudo apt-get install
#
## Configurations
#script: ci/configure.sh
#
## Compilation
#script: ci/compilation.sh
#
## Test
#script: ci/test.sh
#
## Doc compilation
#script: ci/dev_doc.sh
