git:
    depth: 3

branches:
    only:
        - master
        - feat/test_CI

dist: "trusty"

sudo: required

language: 
    - cpp
    - python

python:
    - "3.0"

compiler:
        #        - gcc
        - g++
        #        - clang

os:
    - linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
              #- llvm-toolchain-precise-3.7   # clang
        packages:
            - cmake-data
            - cmake
            - g++-4.9
            - "python3"
              #- clang-3.7
            
              #- doxygen
              #- graphviz

     

before_install:
        - sudo apt-get install libboost-test-dev
          #- sudo apt-get install sphinx-rtd-theme-common

install:
       - mkdir build
       - cd build
       - cmake .. -DENABLE_DOC=YES
       - make
         #- make dev_doc
       - make test
