git:
    depth: 3

branches:
    only:
        - master
        - feat/test_CI

sudo: false


language: 
    - cpp

python:
    - "3.6"

compiler:
        - g++

os:
    - linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
              #- llvm-toolchain-precise-3.7   # clang
        packages:
            - cmake-data
            - cmake
            - g++-4.9
              #- clang-3.7
              #- doxygen
              #- graphviz
matrix:
     include:
        - os: linux
          env: BOOST_VERSION=1.58.0

before_install:
    - pyenv global system 3.6
    - export DOWNLOAD_ROOT="${TRAVIS_BUILD_DIR}/../download"; if [ ! -d "${DOWNLOAD_ROOT}" ]; then mkdir -p "${DOWNLOAD_ROOT}"; fi
    - export BOOST_DOWNLOAD_URL="http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download"
    - export BOOST_ROOT="${TRAVIS_BUILD_DIR}/../boost"
    - export CMAKE_MODULE_PATH="${BOOST_ROOT}"
    - if [ ! -f "${DOWNLOAD_ROOT}/boost.tar.bz2" ]; then wget --no-verbose --output-document="${DOWNLOAD_ROOT}/boost.tar.bz2" "${BOOST_DOWNLOAD_URL}"; fi
    - if [ ! -d "${BOOST_ROOT}" ]; then mkdir -p "${BOOST_ROOT}" && tar jxf "${DOWNLOAD_ROOT}/boost.tar.bz2" --strip-components=1 -C "${BOOST_ROOT}"; fi
    - if [ ! -f "${BOOST_ROOT}/b2" ]; then cd "${BOOST_ROOT}"; ./bootstrap.sh --with-libraries=test; fi
    - cd "${BOOST_ROOT}"; ./b2 --prefix="$BOOST_ROOT" -d0 install

install:
       - cd "${TRAVIS_BUILD_DIR}"
       - pip3 install Sphinx
       - mkdir build
       - cd build
       - cmake .. -DBOOST
       - make
       - make test

         #- make dev_doc

                #  ############################################################################
        #  # Install a recent CMake
        #  ############################################################################
        #    - |
        #            if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        #            CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        #            mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        #            export PATH=${DEPS_DIR}/cmake/bin:${PATH}
        #            else
        #            brew upgrade cmake || brew install cmake
        #            fi
        #    - cmake --version
        #
        #            #  ############################################################################
        #            #  # Install a recent Doxygen
        #            #  ############################################################################
        #            #    - |
        #            #            if [[ "${DOCUMENTATION}" == "true" ]]; then
        #            #            DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.linux.bin.tar.gz"
        #            #            mkdir doxygen && travis_retry wget --quiet -O - ${DOXYGEN_URL} | tar --strip-components=1 -xz -C doxygen
        #            #            export PATH=${DEPS_DIR}/doxygen/bin:${PATH}
        #            #            doxygen --version
        #            #            fi

