virtualenv:
    system_site_packages: true

git:
    depth: 3

branches:
    only:
        - master
        - feat/test_CI

sudo: false

language: cpp

python:
    - "3.6"

compiler: g++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
              #- llvm-toolchain-precise-3.7   # clang
        packages:
            - cmake-data
            - cmake
            - g++-5
              #- clang-3.7
              #- doxygen
              #- graphviz
              #- sphinx_rtd_theme

matrix:
     include:
        - os: linux
          env: BOOST_VERSION=1.58.0

before_install:
    - pyenv global system 3.6
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version
    - export DOWNLOAD_ROOT="${TRAVIS_BUILD_DIR}/../download"; if [ ! -d "${DOWNLOAD_ROOT}" ]; then mkdir -p "${DOWNLOAD_ROOT}"; fi
    - export BOOST_DOWNLOAD_URL="http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download"
    - export BOOST_ROOT="${TRAVIS_BUILD_DIR}/../boost"
    - export CMAKE_MODULE_PATH="${BOOST_ROOT}"
    - if [ ! -f "${DOWNLOAD_ROOT}/boost.tar.bz2" ]; then wget --no-verbose --output-document="${DOWNLOAD_ROOT}/boost.tar.bz2" "${BOOST_DOWNLOAD_URL}"; fi
    - if [ ! -d "${BOOST_ROOT}" ]; then mkdir -p "${BOOST_ROOT}" && tar jxf "${DOWNLOAD_ROOT}/boost.tar.bz2" --strip-components=1 -C "${BOOST_ROOT}"; fi
    - if [ ! -f "${BOOST_ROOT}/b2" ]; then cd "${BOOST_ROOT}"; ./bootstrap.sh --with-libraries=test; fi
    - cd "${BOOST_ROOT}"; ./b2 --prefix="$BOOST_ROOT" -d0 install
    - cmake --version
    - eval "CC=gcc-5 && CXX=g++-5"
    - pip3 install Sphinx numpy
    - python3 --version
    - pip3 freeze | grep 'numpy'

after_failure:
       - cat ${TRAVIS_TEST_RESULT}

install:
      - cd "${TRAVIS_BUILD_DIR}"
      - mkdir build
      - cd build
      - cmake .. -DBUILD_TESTS=ON
      - make
      - python -c "import numpy as np ; print(np.version.version)"
      - python3.6 -c "import numpy as np ; print(np.version.version)"
      - ctest -V

